pipeline {
    agent any
    environment {
        nexus_user = credentials('QDP_nexus_username')
        nexus_password = credentials('QDP_nexus_password')
        nexus_url_snapshot = credentials('nexus_URL_snapshot')
        nexus_url_release = credentials('nexus_URL_release');
    }
    tools {
        jdk 'openjdk16'
    }
    stages {
        stage("Git clone project") {
            steps {
                echo "Git clone.."
                echo "Git url: ${env.URL}"
                echo "Git branch: ${env.BRANCH}"
                git url: "${env.URL}",
                    branch: "${env.BRANCH}",
                    credentialsId: "${env.CREDENTIALS_ID}"
            }
        }
        stage('Setting Release or Snapshot version') {
            steps {
                echo "Pipeline using ${env.MODE} version";
                dir("qdp-core") {
                    script {

                        snapshotVersion = sh (
                            script: " cat build.gradle | grep SNAPSHOT | awk '{print \$3}' | tr -d \\' ",
                            returnStdout: true
                        ).trim()

                        releaseVersion = sh (
                            script: " cat build.gradle | grep RELEASE | awk '{print \$3}' | tr -d \\' ",
                            returnStdout: true
                        ).trim()

                        if (env.MODE == 'SNAPSHOT') {
                            sh "sed -i 's|${releaseVersion}|${snapshotVersion}|g' build.gradle"
                        }
                    }
                }
            }
        }
        stage("Build and Publish") {
            steps {
                echo "Building qdp-core...";
                dir("qdp-core") {
                    script {
                        if (env.MODE == 'SNAPSHOT') {
                            sh './gradlew publish -PmvnUsername=$nexus_user -PmvnPassword=$nexus_password -PmvnURL=$nexus_url_snapshot'
                        } else {
                            sh './gradlew publish -PmvnUsername=$nexus_user -PmvnPassword=$nexus_password -PmvnURL=$nexus_url_release'
                        }
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Clearing...."
            dir("qdp-core") {
                sh "rm -rf build"
            }
        }
    }
}